src/Entity/Volume.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Ghost\GovUkFrontendBundle\Model\ValueUnitInterface;

#[ORM\Embeddable]
class Volume implements ValueUnitInterface
{
    public const UNIT_GALLONS = 'gallons';
    public const UNIT_LITRES = 'litres';

    public const UNIT_TRANSLATION_PREFIX = 'unit.volume.';

    public const UNIT_CHOICES = [
        self::UNIT_TRANSLATION_PREFIX . self::UNIT_LITRES => self::UNIT_LITRES,
        self::UNIT_TRANSLATION_PREFIX . self::UNIT_GALLONS => self::UNIT_GALLONS,
    ];

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2, nullable: true)]
    private ?string $value = null;

    #[ORM\Column(type: Types::STRING, length: 8, nullable: true)]
    private ?string $unit = null;

    #[\Override]
    public function getValue(): ?string
    {
        return $this->value;
    }

    #[\Override]
    public function setValue($value): self
    {
        $this->value = $value;
        return $this;
    }

    #[\Override]
    public function getUnit(): ?string
    {
        return $this->unit;
    }

    #[\Override]
    public function setUnit(?string $unit): self
    {
        $this->unit = $unit;
        return $this;
    }

    #[\Override]
    public function getIsBlank(): bool
    {
        return empty($this->value);
    }
}

src/Form/Admin/DomesticSurvey/AddSurveyType.php
<?php

namespace App\Form\Admin\DomesticSurvey;

use App\Entity\Domestic\Survey;
use App\Form\LongAddressType;
use Ghost\GovUkFrontendBundle\Form\Type as Gds;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddSurveyType extends AbstractType
{
    #[\Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $translationKeyPrefix = "admin.domestic.add-survey";

        $builder
            ->add('registrationMark', Gds\InputType::class, [
                'label' => "{$translationKeyPrefix}.registration-mark.label",
                'help' => "{$translationKeyPrefix}.registration-mark.help",
                'label_attr' => ['class' => 'govuk-label--s'],
                'attr' => ['class' => 'govuk-input--width-10'],
                'disabled' => $options['is_reissue'] || $options['is_resend'],
            ])
            ->add('isNorthernIreland', Gds\ChoiceType::class, [
                'label_attr' => ['class' => 'govuk-label--s'],
                'label' => 'Survey region',
                'attr' => ['class' => 'govuk-radios--inline'],
                'choices' => [
                    'GB' => false,
                    'NI' => true,
                ],
                'disabled' => $options['is_reissue'] || $options['is_resend'],
            ])
            ->add('surveyPeriodStart', Gds\DateType::class, [
                'label' => "{$translationKeyPrefix}.start-date.label",
                'help' => "{$translationKeyPrefix}.start-date.help",
                'label_attr' => ['class' => 'govuk-label--s'],
                'disabled' => $options['is_resend'],
            ])
            ->add('invitationEmails', Gds\EmailType::class, [
                'label' => "{$translationKeyPrefix}.invitation-email.label",
                'help' => "{$translationKeyPrefix}.invitation-email.help",
                'label_attr' => ['class' => 'govuk-label--s'],
            ])
            ->add('invitationAddress', LongAddressType::class, [
                'label' => "{$translationKeyPrefix}.invitation-address.label",
                'help' => "{$translationKeyPrefix}.invitation-address.help",
                'label_attr' => ['class' => 'govuk-label--s'],
            ])
            ->add('submit', Gds\ButtonType::class, [
                'type' => 'submit',
                'label' => $options['is_resend'] ?
                    "{$translationKeyPrefix}.submit.resend-label" :
                    "{$translationKeyPrefix}.submit.label",
            ]);
    }

    #[\Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Survey::class,
            'validation_groups' => ['add_survey', 'notify_api'],
            'is_reissue' => false,
            'is_resend' => false,
        ]);
    }
}

src/Form/Admin/DomesticSurvey/ConfirmApprovedActionType.php
<?php

namespace App\Form\Admin\DomesticSurvey;

use App\Entity\Domestic\Survey;
use Ghost\GovUkFrontendBundle\Form\Type as Gds;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConfirmApprovedActionType extends AbstractType
{
    #[\Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $translationKeyPrefix = $options['translation_key_prefix'];

        $builder
            ->add('reasonForUnfilledSurvey', Gds\ChoiceType::class, [
                'choices' => Survey::UNFILLED_SURVEY_REASON_CHOICES,
                'choice_translation_domain' => 'messages',
                'label_attr' => ['class' => 'govuk-label--s'],
            ])
            ->add('confirm', Gds\ButtonType::class, array_merge($options['confirm_button_options'], [
                'type' => 'submit',
                'label' => "{$translationKeyPrefix}.confirm.label",
            ]))
            ->add('cancel', Gds\ButtonType::class, [
                'type' => 'submit',
                'label' => "{$translationKeyPrefix}.cancel.label",
                'attr' => ['class' => 'govuk-button--secondary'],
            ])
        ;
    }

    #[\Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Survey::class,
            'confirm_button_options' => [],
            'validation_groups' => ['admin_reason_for_unfilled_survey'],
        ]);

        $resolver->setRequired([
            'translation_key_prefix',
        ]);
    }
}

src/Form/Admin/DomesticSurvey/Edit/AbstractStopType.php
<?php

namespace App\Form\Admin\DomesticSurvey\Edit;

use App\Entity\AbstractGoodsDescription;
use App\Entity\CargoType;
use App\Entity\Distance;
use App\Entity\Domestic\Day;
use App\Entity\Domestic\DayStop;
use App\Entity\Domestic\DaySummary;
use App\Form\DomesticSurvey\AbstractDistanceTravelledType;
use App\Form\DomesticSurvey\DayStop as DayStopForms;
use App\Form\DomesticSurvey\DaySummary as DaySummaryForms;
use Ghost\GovUkFrontendBundle\Form\Type\ValueUnitType;
use App\Utility\HazardousGoodsHelper;
use Ghost\GovUkFrontendBundle\Form\Type as Gds;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\Validator\Constraints\GroupSequence;
use Symfony\Contracts\Translation\TranslatorInterface;

abstract class AbstractStopType extends AbstractType implements DataMapperInterface
{
    protected string $dataClass;

    public function __construct(protected TranslatorInterface $translator, protected HazardousGoodsHelper $hazardousGoodsHelper)
    {}

    #[\Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $this->dataClass = $options['data_class'];
        $builder->setDataMapper($this);

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options) {
            $isNorthernIreland = $this->isNorthernIreland($event->getData());

            $yesTransferChoices = array_flip(array_map(
                fn($v) => "Yes, via " . strtolower($this->translator->trans($v)),
                array_flip(Day::TRANSFER_CHOICES)
            ));

            $transferChoices = array_merge($yesTransferChoices, ['No' => false]);

            if ($options['is_add_form']) {
                $transferChoices = ['' => null] + $transferChoices;
            }

            $event->getForm()
                ->add('originLocation', Gds\InputType::class, [
                    'label_attr' => ['class' => 'govuk-label--s'],
                ])
                ->add('goodsTransferredFrom', Gds\ChoiceType::class, [
                    'label' => 'Were goods loaded?',
                    'label_attr' => ['class' => 'govuk-label--s'],
                    'choices' => $transferChoices,
                    'expanded' => false,
                ])
                ->add('destinationLocation', Gds\InputType::class, [
                    'label_attr' => ['class' => 'govuk-label--s'],
                ])
                ->add('goodsTransferredTo', Gds\ChoiceType::class, [
                    'label' => 'Were goods unloaded?',
                    'label_attr' => ['class' => 'govuk-label--s'],
                    'choices' => $transferChoices,
                    'expanded' => false,
                ]);

            if ($this->dataClass === DaySummary::class) {
                $event->getForm()->add('furthestStop', Gds\InputType::class, [
                    'label_attr' => ['class' => 'govuk-label--s'],
                ]);
            }

            // border crossing
            if ($isNorthernIreland) {
                $event->getForm()
                    ->add('borderCrossingLocation', Gds\InputType::class, [
                        'label' => 'domestic.day-stop.border-crossing.border-crossing-location.label',
                        'label_attr' => ['class' => 'govuk-label--s'],
                    ]);
            }

            switch ($this->dataClass) {
                case DaySummary::class :
                    $event->getForm()
                        ->add('distanceTravelled', DaySummaryForms\DistanceTravelledType::class, [
                            'inherit_data' => true,
                            'label' => false,
                        ]);
                    break;
                case DayStop::class :
                    $event->getForm()
                        ->add('distanceTravelled', ValueUnitType::class, [
                            'label' => "domestic.day-stop.distance-travelled.distance-travelled.label",
                            'label_attr' => ['class' => 'govuk-label--s'],
                            'value_form_type' => Gds\DecimalType::class,
                            'value_options' => AbstractDistanceTravelledType::VALUE_OPTIONS,
                            'unit_options' => AbstractDistanceTravelledType::UNIT_OPTIONS,
                            'data_class' => Distance::class,
                        ]);
                    break;
            }

            [$goodsChoices, $goodsChoiceOptions] = AbstractGoodsDescription::getFormChoicesAndOptions($this->dataClass === DaySummary::class);
            [$hazardousChoices, $hazardousChoiceOptions] = $this->hazardousGoodsHelper->getFormChoicesAndOptions(true, true, false);
            [$cargoChoices, $cargoChoiceOptions] = CargoType::getFormChoicesAndOptions();

            $hazardousChoices = ['' => null] + $hazardousChoices;
            $cargoChoices = ['' => null] + $cargoChoices;

            $emptyKey = AbstractGoodsDescription::GOODS_DESCRIPTION_TRANSLATION_PREFIX . AbstractGoodsDescription::GOODS_DESCRIPTION_EMPTY;
            $goodsChoiceOptions[$emptyKey] = array_merge(
                ($goodsChoiceOptions[$emptyKey] ?? []), [
                    'conditional_hide_form_names' => [
                        'hazardousGoodsCode', 'cargoTypeCode', 'goodsWeight', 'numberOfStops',
                    ],
                ]);

            $event->getForm()
                ->add('goodsDescription', Gds\ChoiceType::class, [
                    'choices' => $goodsChoices,
                    'choice_options' => $goodsChoiceOptions,
                    'label' => "Goods carried",
                    'label_attr' => ['class' => 'govuk-fieldset__legend--s'],
                ])
                ->add('goodsDescriptionOther', Gds\InputType::class, [
                    'label' => false,
                    'help' => "goods.description.help.other",
                ])
                ->add('hazardousGoodsCode', Gds\ChoiceType::class, [
                    'expanded' => false,
                    'choices' => $hazardousChoices,
                    'choice_options' => $hazardousChoiceOptions,
                    'label' => "Were these goods dangerous or hazardous?",
                    'label_attr' => ['class' => 'govuk-label--s'],
                    'label_html' => true,
                ])
                ->add('cargoTypeCode', Gds\ChoiceType::class, [
                    'expanded' => false,
                    'choices' => $cargoChoices,
                    'choice_options' => $cargoChoiceOptions,
                    'label' => "How were the goods carried?",
                    'label_attr' => ['class' => 'govuk-label--s'],
                ]);
            switch ($this->dataClass) {
                case DaySummary::class :
                    $event->getForm()
                        ->add('goodsWeight', DaySummaryForms\GoodsWeightType::class, [
                            'inherit_data' => true,
                            'label' => false,
                        ])
                        ->add('numberOfStops', DaySummaryForms\NumberOfStopsType::class, [
                            'inherit_data' => true,
                            'label' => 'Number of stops',
                            'label_attr' => ['class' => 'govuk-label--m'],
                        ]);
                    break;
                case DayStop::class :
                    $event->getForm()
                        ->add('goodsWeight', DayStopForms\GoodsWeightType::class, [
                            'inherit_data' => true,
                            'label' => false,
                        ]);
                    break;
            }

            $event->getForm()
                ->add('submit', Gds\ButtonType::class, [
                    'label' => 'Save changes',
                ])
                ->add('cancel', Gds\ButtonType::class, [
                    'label' => 'Cancel',
                    'attr' => ['class' => 'govuk-button--secondary'],
                ]);
        });
    }

    protected function isNorthernIreland($stop) {
        return $stop->getDay()->getResponse()->getSurvey()->getIsNorthernIreland();
    }

    #[\Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setAllowedValues('data_class', [DayStop::class, DaySummary::class]);

        $resolver->setDefault('is_northern_ireland', fn(FormInterface $form) => $this->isNorthernIreland($form->getData()));

        $resolver->setDefault('validation_groups', function(FormInterface $form) {
            /** @var DayStop $stop */
            $stop = $form->getData();
            $groups = [
                'admin-day-stop',
                new GroupSequence(['admin-day-summary', 'admin-day-summary.total-stops']),
            ];

            if ($this->isNorthernIreland($stop)) {
                $groups[] = 'admin-day-stop-ni';
            }

            if ($stop->getGoodsLoaded()) {
                $groups[] = 'admin-day-stop-loaded';
            }

            if ($stop->getGoodsUnloaded()) {
                $groups[] = 'admin-day-stop-unloaded';
            }

            if ($stop->getGoodsDescription() !== AbstractGoodsDescription::GOODS_DESCRIPTION_EMPTY) {
                $groups[] = 'admin-day-stop-not-empty';
            }

            return $groups;
        });

        $resolver->setDefault('is_add_form', false);

        $resolver->setDefault('error_mapping', [
            'number-of-stops' => 'numberOfStops',
        ]);
    }

    #[\Override]
    public function mapDataToForms($viewData, $forms): void
    {

src/Form/Admin/DomesticSurvey/Edit/BusinessAndVehicleDetailsType.php
<?php

namespace App\Form\Admin\DomesticSurvey\Edit;

use App\Entity\Domestic\SurveyResponse;
use App\Form\DomesticSurvey\VehicleAndBusinessDetails\BusinessDetailsType as EmbeddedBusinessDetailsType;
use Ghost\GovUkFrontendBundle\Form\Type as Gds;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BusinessAndVehicleDetailsType extends AbstractType
{
    #[\Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('business_details', EmbeddedBusinessDetailsType::class, [
                'inherit_data' => true,
                'label' => false,
                'expanded_employees' => false,
                'add_form' => true,
                'validation_groups' => $options['validation_groups'],
            ])
            ->add('vehicle_details', VehicleDetailsType::class, [
                'inherit_data' => true,
                'label' => false,
                'include_buttons' => false,
                'add_form' => true,
                'validation_groups' => $options['validation_groups'],
            ])
            ->add('submit', Gds\ButtonType::class, [
                'label' => 'Save changes',
            ])
            ->add('cancel', Gds\ButtonType::class, [
                'label' => 'Cancel',
                'attr' => ['class' => 'govuk-button--secondary'],
            ]);
    }

    #[\Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SurveyResponse::class,
            'validation_groups' => ['admin_vehicle', 'admin_business_details'],
        ]);
    }
}

templates/domestic_survey/includes/business-details.html.twig
{%- from '@GhostGovUkFrontend/components/macros.html.twig' import summaryListStart, summaryListEnd, summaryListRow -%}
{%- set showActions = showActions ?? true -%}

{%- set businessDetailsActionLinks = [
    {
        href: url('app_domesticsurvey_vehicleandbusinessdetails_index', {state: constant('App\\Workflow\\DomesticSurvey\\VehicleAndBusinessDetailsState::STATE_CHANGE_BUSINESS_DETAILS')}),
        text: 'common.actions.change' | trans,
        visuallyHiddenText: 'domestic.survey-response.business-details.heading' | trans
    }
] -%}

<h2 class="govuk-heading-m">Business details</h2>
{{- summaryListStart({classes: 'govuk-!-margin-bottom-' ~ (marginBottom ?? 9)}) -}}
    {{- summaryListRow({
        key: 'domestic.survey-response.business-details.number-of-employees.label' | trans,
        value: "common.number-of-employees.#{survey.response.numberOfEmployees}" | trans,
        actions: showActions ? businessDetailsActionLinks : []
    }, showActions) }}
    {{- summaryListRow({
        key: 'domestic.survey-response.business-details.business-nature.label' | trans,
        value: survey.response.businessNature,
        actions: showActions ? businessDetailsActionLinks : []
    }, showActions) }}
    {{- summaryListRow({
        key: 'domestic.survey-response.business-details.operation-type.label' | trans,
        value: (constant('App\\Entity\\Vehicle::OPERATION_TYPE_TRANSLATION_PREFIX') ~ survey.response.vehicle.operationType) | trans,
        actions: showActions ? businessDetailsActionLinks : []
    }, showActions) }}
{{- summaryListEnd() -}}

templates/domestic_survey/includes/contact-details.html.twig
{%- from '@GhostGovUkFrontend/components/macros.html.twig' import summaryListStart, summaryListEnd, summaryListRow -%}
{%- set showActions = showActions ?? true -%}

{{- summaryListStart({classes: 'govuk-!-margin-bottom-' ~ (marginBottom ?? 1)}) -}}
    {%- set contactDetailsActionLinks = [
        {
            href: url('app_domesticsurvey_initialdetails_index', {state: constant('App\\Workflow\\DomesticSurvey\\InitialDetailsState::STATE_CHANGE_CONTACT_DETAILS')}),
            text: 'common.actions.change' | trans,
            visuallyHiddenText: 'domestic.survey-response.contact-details.heading' | trans
        }
    ] -%}

    {{- summaryListRow({
        key: 'domestic.survey-response.contact-details.business-name.label' | trans,
        value: survey.response.contactBusinessName | default('-'),
        actions: showActions ? contactDetailsActionLinks : []
    }, showActions) -}}
    {{- summaryListRow({
        key: 'domestic.survey-response.contact-details.contact-name.label' | trans,
        value: survey.response.contactName | default('-'),
        actions: showActions ? contactDetailsActionLinks : []
    }, showActions) -}}
    {{- summaryListRow({
        key: 'domestic.survey-response.contact-details.contact-telephone.label' | trans,
        value: survey.response.contactTelephone | default('-'),
        actions: showActions ? contactDetailsActionLinks : []
    }, showActions) -}}
    {{- summaryListRow({
        key: 'domestic.survey-response.contact-details.contact-email.label' | trans,
        value: survey.response.contactEmail | default('-'),
        actions: showActions ? contactDetailsActionLinks : []
    }, showActions) -}}
{{- summaryListEnd() -}}

templates/domestic_survey/includes/day-stop.html.twig
{%- from '@GhostGovUkFrontend/components/macros.html.twig' import buttonLink, summaryListStart, summaryListEnd, summaryListRow -%}
{%- from 'macros.html.twig' import displayHazardousGoods -%}
{%- set showActions = showActions ?? true -%}

{{- summaryListStart({classes: 'govuk-!-margin-bottom-' ~ (marginBottom ?? 9)}) -}}
    {%- set params = {dayNumber: day.number, stopNumber: stop.number} -%}
    {%- set suffixParams = {stopNumber: stop.number} -%}
    {%- set locationsChangeLink = [
        {
            href: url('app_domesticsurvey_daystop_start', params),
            text: 'common.actions.change' | trans,
            visuallyHiddenText: 'domestic.day-view.detailed-change-link-sr-suffix.locations' | trans(suffixParams)
        }
    ] -%}

    {{- summaryListRow({
            key: 'domestic.day-view.start-location' | trans,
            value: (stop.originLocation | formatPotentialPostcode | default('-')) ~ (stop | formatGoodsTransferDetails('loading', ' — ')),
            actions: showActions ? locationsChangeLink : []
    }, showActions) -}}
    {{- summaryListRow({
        key: 'domestic.day-view.destination-location' | trans,
        value: (stop.destinationLocation | formatPotentialPostcode | default('-')) ~ (stop | formatGoodsTransferDetails('unloading', ' — ')),
        actions: showActions ? locationsChangeLink : []
    }, showActions) -}}
    {%- if stop.day.response.survey.isNorthernIreland -%}
        {{- summaryListRow({
            key: 'domestic.day-view.border-crossing' | trans,
            value: stop.borderCrossingLocation | formatPotentialPostcode | default('-'),
            actions: showActions ? locationsChangeLink : []
        }, showActions) -}}
    {%- endif -%}

    {%- set params = params | merge({state: constant('App\\Workflow\\DomesticSurvey\\DayStopState::STATE_DISTANCE_TRAVELLED')}) -%}
    {%- set distanceChangeLink = [
        {
            href: url('app_domesticsurvey_daystop_wizard', params),
            text: 'common.actions.change' | trans,
            visuallyHiddenText: 'domestic.day-view.detailed-change-link-sr-suffix.distance-travelled' | trans(suffixParams)
        }
    ] -%}
    {%- set distanceValue = stop.distanceTravelled.isBlank ?
        '-' :
        ("common.distance.#{stop.distanceTravelled.unit}" | trans({value: stop.distanceTravelled.value}))
    -%}

    {{- summaryListRow({
        key: 'domestic.day-view.distance-travelled' | trans,
            value: distanceValue,
            actions: showActions ? distanceChangeLink : []
    }, showActions) -}}

    {%- set params = params | merge({state: constant('App\\Workflow\\DomesticSurvey\\DayStopState::STATE_GOODS_DESCRIPTION')}) -%}
    {%- set goodsChangeLink = [
        {
            href: url('app_domesticsurvey_daystop_wizard', params),
            text: 'common.actions.change' | trans,
            visuallyHiddenText: 'domestic.day-view.detailed-change-link-sr-suffix.goods-description' | trans(suffixParams)
        }
    ] -%}

    {%- set goodsCarriedValue -%}
        {{- stop | formatGoodsDescription -}}
        {%- if stop.hazardousGoodsCode %} — {{ displayHazardousGoods(stop.hazardousGoodsCode) }}{%- endif -%}
    {%- endset -%}
    {{- summaryListRow({
        key: 'domestic.day-view.goods-carried' | trans,
        value: {html: goodsCarriedValue},
        actions: showActions ? goodsChangeLink : []
    }, showActions) -}}

    {%- if stop.goodsDescription != constant('App\\Entity\\AbstractGoodsDescription::GOODS_DESCRIPTION_EMPTY') -%}
        {%- set cargoChoices = constant('App\\Entity\\CargoType::CHOICES') -%}
        {{- summaryListRow({
            key: 'domestic.day-view.cargo-type' | trans,
            value: choiceLabel(cargoChoices, stop.cargoTypeCode) | trans,
            actions: showActions ? goodsChangeLink : []
        }, showActions) -}}

        {%- set wasLimitedBy -%}
            {%- set factors = stop.wasLimitedBy -%}
            {%- if factors is not empty %} — {{ ('domestic.day-view.limited-by.' ~ (factors | join('-and-'))) | trans }}{% endif -%}
        {%- endset -%}

        {%- set params = params | merge({state: constant('App\\Workflow\\DomesticSurvey\\DayStopState::STATE_GOODS_WEIGHT')}) -%}
        {%- set weightChangeLink = [
            {
                href: url('app_domesticsurvey_daystop_wizard', params),
                text: 'common.actions.change' | trans,
                visuallyHiddenText: 'domestic.day-view.detailed-change-link-sr-suffix.goods-weight' | trans(suffixParams)
            }
        ] -%}
        {{- summaryListRow({
            key: 'domestic.day-view.weight-of-goods.label' | trans,
            value: ("common.weight.kilograms" | trans({value: stop.weightOfGoodsCarried})) ~ wasLimitedBy,
            actions: showActions ? weightChangeLink : []
        }, showActions) -}}
    {%- endif -%}
{{- summaryListEnd() -}}

templates/domestic_survey/includes/day-stops-table.html.twig
{%- from '@GhostGovUkFrontend/components/macros.html.twig' import tableStart, tableBodyStart, tableEndIncludingBody, tableHead, tableRow -%}
{%- set linkRowNumbers = linkRowNumbers | default(false) -%}
{{- tableStart({classes: 'rfs-admin-report-table'}) -}}
    {{- tableHead([
        '#',
        'From',
        'To',
        'Goods',
    ]) -}}
    {%- set stopCount = stops | length -%}
    {{- tableBodyStart() -}}
        {%- for stop in stops -%}
            {%- set link %}<a href="#stop-{{ stop.number }}" class="govuk-link">{{ stop.number }}</a>{% endset -%}
            {{- tableRow([
                linkRowNumbers ? {html: link} : stop.number,
                ((stop.originLocation | formatPotentialPostcode) ~ (stop | formatGoodsTransferDetails('loading', ' — '))),
                ((stop.destinationLocation | formatPotentialPostcode) ~ (stop | formatGoodsTransferDetails('unloading', ' — '))),
                stop | formatGoodsDescription(true),
            ]) -}}
        {%- endfor -%}
        {%- if stopCount < 4 -%}
            {%- for x in (stopCount + 1)..4 -%}
                {{- _self.emptyRow(x) -}}
            {%- endfor -%}
        {%- endif -%}
        {{- _self.emptyRow(stopCount < 5 ? 5 : (stopCount + 1)) -}}
{{- tableEndIncludingBody() -}}

{%- macro emptyRow(rowNumber) -%}
    {{- tableRow([rowNumber, '-', '-', '-']) -}}
{%- endmacro -%}

templates/domestic_survey/includes/macros.html.twig
{% macro dayText(day) -%}
    {{- (day | default(false))
        ? (day.hasMoreThanFiveStops
            ? ('6 stops or more' ~ (day.isComplete
                ? " (#{day.summary.originLocation|formatPotentialPostcode} to #{day.summary.destinationLocation|formatPotentialPostcode})"
                : ' (incomplete)'
            ))
            : ('5 stops or fewer' ~ (day.isComplete
                ? " (#{(day.stops | first).originLocation|formatPotentialPostcode} to #{(day.stops | last).destinationLocation|formatPotentialPostcode})"
                : " (incomplete)"
            ))
        )
        : 'No journeys'
    -}}
{%- endmacro %}

{% macro userAssitanceHelpBlock() %}
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">{{ 'common.help.summary'|trans }}</span>
        </summary>
        <div class="govuk-details__text">
            <p class="govuk-body">{{ 'common.help.text.call'|trans }} <strong>{{ 'domestic.help.text.phone-number'|trans }}</strong></p>
            <p class="govuk-body">{{ 'common.help.text.office-hours'|trans }}</p>
        </div>
    </details>
{% endmacro %}